# Generated by Django 5.2 on 2025-04-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
