# Generated by Django 5.2 on 2025-04-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards_app', '0003_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
