# Generated by Django 5.2 on 2025-04-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards_app', '0006_alter_user_avatar_cardset_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='term',
            field=models.CharField(max_length=100),
        ),
    ]
