# Generated by Django 5.2 on 2025-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards_app', '0008_alter_card_definition_alter_cardset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardset',
            name='bg_color',
        ),
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='card',
            name='term',
            field=models.CharField(max_length=50),
        ),
    ]
