# Generated by Django 5.2 on 2025-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards_app', '0009_remove_cardset_bg_color_alter_card_definition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cardset',
            name='created_at',
        ),
        migrations.AddField(
            model_name='card',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
