# Generated by Django 5.2 on 2025-04-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_with_cards_app', '0010_remove_card_created_at_remove_cardset_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_answered',
        ),
    ]
